
/**************************************************************
 *	
 *	fucking_noot_noot, 8 bit, 11025Hz,
 *	1 channel, 16064 bytes/channel
 *	Total Size: 1 * 16064 + 4 (header) = 16108 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Documents\georgia tech\Year 3\Media Device Architecture\2261FinalProject\Music\noot wav\fucking-noot-noot.wav
 *	Time-stamp: Tue Nov 26 13:04:18 2019
 *	
 **************************************************************/

#ifndef __FUCKING_NOOT_NOOTH__
#define __FUCKING_NOOT_NOOTH__

#define FUCKING_NOOT_NOOTFREQ 11025
#define FUCKING_NOOT_NOOTLEN 16064

extern const unsigned char fucking_noot_noot[16064];

#endif /* __FUCKING_NOOT_NOOTH__ */
