
/**************************************************************
 *	
 *	noot5, 8 bit, 11025Hz,
 *	1 channel, 8055 bytes/channel
 *	Total Size: 1 * 8055 + 4 (header) = 8099 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Documents\georgia tech\Year 3\Media Device Architecture\2261FinalProject\Music\noot wav\noot5.wav
 *	Time-stamp: Tue Nov 26 12:53:50 2019
 *	
 **************************************************************/

#ifndef __NOOT5H__
#define __NOOT5H__

#define NOOT5FREQ 11025
#define NOOT5LEN 8055

extern const unsigned char noot5[8055];

#endif /* __NOOT5H__ */
