
/**************************************************************
 *	
 *	endThemeSong, 8 bit, 11025Hz,
 *	1 channel, 1164744 bytes/channel
 *	Total Size: 1 * 1164744 + 4 (header) = 1164788 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Documents\georgia tech\Year 3\Media Device Architecture\2261FinalProject\Music\endThemeSong.wav
 *	Time-stamp: Fri Nov 29 15:08:04 2019
 *	
 **************************************************************/

#ifndef __ENDTHEMESONGH__
#define __ENDTHEMESONGH__

#define ENDTHEMESONGFREQ 11025
#define ENDTHEMESONGLEN 1164744

extern const unsigned char endThemeSong[1164744];

#endif /* __ENDTHEMESONGH__ */
