
/**************************************************************
 *	
 *	grenzlinie, 8 bit, 11025Hz,
 *	1 channel, 415842 bytes/channel
 *	Total Size: 1 * 415842 + 4 (header) = 415886 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Documents\georgia tech\Year 3\Media Device Architecture\2261FinalProject\Music\grenzlinie.wav
 *	Time-stamp: Tue Nov 26 11:50:21 2019
 *	
 **************************************************************/

#ifndef __GRENZLINIEH__
#define __GRENZLINIEH__

#define GRENZLINIEFREQ 11025
#define GRENZLINIELEN 415842

extern const unsigned char grenzlinie[415842];

#endif /* __GRENZLINIEH__ */
