
/**************************************************************
 *	
 *	keepOnKeepingOn, 8 bit, 44100Hz,
 *	1 channel, 10214784 bytes/channel
 *	Total Size: 1 * 10214784 + 4 (header) = 10215024 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Documents\georgia tech\Year 3\Media Device Architecture\2261FinalProject\Music\keepOnKeepingOn.wav
 *	Time-stamp: Sat Nov 09 11:55:37 2019
 *	
 **************************************************************/

#ifndef __KEEPONKEEPINGONH__
#define __KEEPONKEEPINGONH__

#define KEEPONKEEPINGONFREQ 44100
#define KEEPONKEEPINGONLEN 10214784

extern const unsigned char keepOnKeepingOn[10214784];

#endif /* __KEEPONKEEPINGONH__ */
