
/**************************************************************
 *	
 *	keepOnKeepingOn, 8 bit, 11025Hz,
 *	1 channel, 2553696 bytes/channel
 *	Total Size: 1 * 2553696 + 4 (header) = 2553740 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Documents\georgia tech\Year 3\Media Device Architecture\2261FinalProject\Music\keepOnKeepingOn.wav
 *	Time-stamp: Tue Nov 26 11:16:47 2019
 *	
 **************************************************************/

#ifndef __KEEPONKEEPINGONH__
#define __KEEPONKEEPINGONH__

#define KEEPONKEEPINGONFREQ 11025
#define KEEPONKEEPINGONLEN 2553696

extern const unsigned char keepOnKeepingOn[2553696];

#endif /* __KEEPONKEEPINGONH__ */
