
/**************************************************************
 *	
 *	shotgun_shot, 8 bit, 11025Hz,
 *	1 channel, 21971 bytes/channel
 *	Total Size: 1 * 21971 + 4 (header) = 22015 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Documents\georgia tech\Year 3\Media Device Architecture\2261FinalProject\Music\shotgun_shot.wav
 *	Time-stamp: Tue Nov 26 11:22:37 2019
 *	
 **************************************************************/

#ifndef __SHOTGUN_SHOTH__
#define __SHOTGUN_SHOTH__

#define SHOTGUN_SHOTFREQ 11025
#define SHOTGUN_SHOTLEN 21971

extern const unsigned char shotgun_shot[21971];

#endif /* __SHOTGUN_SHOTH__ */
