
/**************************************************************
 *	
 *	noot7, 8 bit, 11025Hz,
 *	1 channel, 16028 bytes/channel
 *	Total Size: 1 * 16028 + 4 (header) = 16072 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Documents\georgia tech\Year 3\Media Device Architecture\2261FinalProject\Music\noot wav\noot7.wav
 *	Time-stamp: Tue Nov 26 12:55:37 2019
 *	
 **************************************************************/

#ifndef __NOOT7H__
#define __NOOT7H__

#define NOOT7FREQ 11025
#define NOOT7LEN 16028

extern const unsigned char noot7[16028];

#endif /* __NOOT7H__ */
